spring:
  application:
  name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/webproj
    username: postgres
    password: quanbro7
    driver-class-name: org.postgresql.Driver

  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always
